PATH_SEGMENT_CLASS_INDEX = -2

IMAGE_HEIGHT = 224
IMAGE_WIDTH = 224
IMAGE_CHANNELS = 3

IMAGE_SIZE = [IMAGE_HEIGHT, IMAGE_WIDTH]

SHUFFLE_TRAIN_DATASET = True
SHUFFLE_VALIDATION_DATASET = False

REPORT_STEP = 20
